// layout.js
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import ResponsiveAppBar from "./(component)/Header";

// Load fonts and define as CSS variables
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// Metadata for the app
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      {/* Apply fonts using CSS variables */}
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        {/* AppBar moved here - must be client-safe */}
        <ResponsiveAppBar />
        {children}
      </body>
    </html>
  );
}
